### PR TITLE
#162948947 Setup React Redux

### PR DESCRIPTION
**Pull request by Nyakaru**
**What does this PR do?**

* Setup React/Redux

**Description of the tasks to be completed?**

* Create a file structure for Redux workflow.
* Add packages `redux, react-redux, redux-thunk`
* Add dev dependencies `redux-immutable-state-invariant, redux-logger, redux-devtools-extension`
* Create the Redux store

#### How should this be manually tested?
* Git clone this repo: `git clone https://github.com/andela/ah-fulldeck-frontend.git`
* Git checkout to ch-setup-redux-162948947
* Make sure have the redux dev tool extension
* npm start :-This should open up a browser tab
* Click on the redux dev tools icon on the browser
* This should open up the empty redux store - make sure it looks like the screenshot below.

#### What are the relevant pivotal tracker stories?
[162948947](https://www.pivotaltracker.com/story/show/162948947)

#### Screenshots
screenshot 2019-02-07 at 09 20 36

### CODE REVIEW

**Review by Hesbon5600 — DISMISSED** [review]
Working perfectly

**Review by Nicanor008 — COMMENTED** [review]
for future use, the component's files should all be named with `.jsx` extensions and also following the PascalCase convention. like `TestPage.jsx` for two worded filename and `Test.jsx` for single worded filename.
Otherwise, the functionality works well.

**Review by eduhmik — DISMISSED** [review]

**Review by Nicanor008 — DISMISSED** [review]

**Review by JoshuaKodhe — DISMISSED** [review]

**Review by Nicanor008 — DISMISSED** [review]

**Review by Nicanor008 — DISMISSED** [review]

**Review by charitymarani — DISMISSED** [review]

**Review by charitymarani — DISMISSED** [review]

**Review by JoshuaKodhe — DISMISSED** [review]

**Review by Nicanor008 — DISMISSED** [review]

**Review by charitymarani — DISMISSED** [review]

**Review by Hesbon5600 — DISMISSED** [review]

**Review by Nicanor008 — DISMISSED** [review]

**Comment by victorjambo** [comment]
@Nyakaru Tests are failing because `src/components/test.js` has no tests in it. Remove the test file or write a smoke test.

**Comment by Nyakaru** [comment]
> @Nyakaru Tests are failing because `src/components/test.js` has no tests in it. Remove the test file or write a smoke test.

Okay i have fixed that

**Review by JoshuaKodhe — APPROVED** [review]

**Review by Nicanor008 — APPROVED** [review]

**Review by charitymarani — APPROVED** [review]

**Pull request merged**
